### ISSUE TITLE
Bad dictionary reference in 2.1.6

### ISSUE THREAD

**Issue by iloveitaly** [Doist/todoist-api-python#152]
## Bug description

```
> /Users/mike/Projects/productivity/clean-workspace/.venv/lib/python3.12/site-packages/todoist_api_python/models.py(37)from_dict()
     32             id=obj["id"],
     33             is_favorite=obj["is_favorite"],
     34             is_inbox_project=obj["is_inbox_project"],
     35             is_shared=obj["is_shared"],
     36             is_team_inbox=obj["is_team_inbox"],
---> 37             can_assign_tasks=obj["can_assign_tasks"],
     38             name=obj["name"],
     39             order=obj["order"],
     40             parent_id=obj.get("parent_id"),
     41             url=obj["url"],

```

## Is reproducible
Yes.

## To reproduce
Use 2.1.6 and not 2.1.5

## Version information:
- Package version: 2.1.6
- Python version: 3.12.5

**Comment by olliebeannn** [comment]
@iloveitaly Is this causing you to get 'can_assign_tasks` as the response to some operations, e.g. `get_projects()` and `add_project()`? I'm running into this, but get_projects works fine with 2.1.5, and also with `curl`.

**Comment by lefcha** [comment]
There was a regression, please update to version [2.1.7](https://pypi.org/project/todoist-api-python/2.1.7/).
