### ISSUE TITLE
Returning None for Task.due for tasks with only date set (not date and time)

### ISSUE THREAD

**Issue by gregyjames** [Doist/todoist-api-python#157]
## Bug description
I have a task with only a date, when I try pulling it with the library using gettasks() it is returning none for the due attribute. It only appears for returning Task.due for tasks with date and time set.

## Expected behaviour
Task is pulled in, task.due is not None. Based on the API guide, I would expect task.due.date to have a value but task.due.datetime to be empty.

## Is reproducible
Yes

## To reproduce
1. Create task with date only
2. Try pulling it in
3. Check due for null

## Steps taken to try to reproduce
Attempted to create multiple tasks with date only but they never pulled in the values.

## Screenshots
N/A

## Version information:
- Package version: 2.1.7
- Python version: 3.12

## Additional information
N/A

**Comment by lefcha** [comment]
I can't reproduce based on the steps above.

Example task:

![image](https://github.com/user-attachments/assets/a561c870-0aeb-48b9-9b6c-ccaabf751898)

Getting it:

```py
>>> from todoist_api_python.api import TodoistAPI
>>> api = TodoistAPI(TOKEN)
>>> api.get_task(task_id="8291811638").due
Due(date='2024-10-02',
    is_recurring=False,
    string='2 Oct',
    datetime=None,
    timezone=None)
>>>
```

Can you share an example?

**Comment by gregyjames** [comment]
Apologies, it appears that this was an issue on my end in converting the string back to a datetime object. The simpler example helped clear it up, thanks. Closing this now.
