### ISSUE TITLE
pip install todoist-api-python - not working

### ISSUE THREAD

**Issue by jayeshdesai4520** [Doist/todoist-api-python#17]
I am using this command "pip install todoist-api-python" to install the library but, it is showing me an error
https://imgur.com/TCb3SlZ

**Comment by sadikkuzu** [comment]
Hi @jayeshdesai4520 
What's your python version?

You can get via `python -V`

---

This package supports 

https://github.com/Doist/todoist-api-python/blob/89b601b8edad47bc999cd7b2ab36c5e2a9f8cd8a/pyproject.toml#L20-L21

**Comment by jayeshdesai4520** [comment]
Hello @sadikkuzu  , my python version is 3.7 but never mind I have used requests library and now it is working!

**Comment by sadikkuzu** [comment]
Well, actually, I am not in the Doist team. You can close your own issue btw:)
Have a nice day.
Enjoy coding! :)
