### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by stkeky** [Doist/todoist-api-python#7]
Hey 👋🏻

I tried using the SDK and following problem occurred as trying to retrieve tasks (by the example provided [here](https://github.com/Doist/todoist-api-python#usage)):

```python
Traceback (most recent call last):
  File "/home/censored/main.py", line 2, in <module>
    from todoist_api_python.api import TodoistAPI
  File "/home/censored/env/lib/python3.9/site-packages/todoist_api_python/api.py", line 17, in <module>
    from todoist_api_python.models import (
  File "/home/censored/env/lib/python3.9/site-packages/todoist_api_python/models.py", line 3, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

The `todoist-api-python==1.1.0` was the only dependency in the project (brand new `virtualenv`, Python 3.9). 

Problem was solved by adding the `attrs` package (`pip install attrs`). So, this should probably be addressed in README.md or `attrs` should be added as dependency?

Additionally, maybe you should consider adding the template for new issues on Github, so it's easier for both reporting and debuging.

All the best, thanks. 😄

**Comment by mmuejde** [comment]
Hey,
I had also the same problem. 
Thanks @stkeky
